lib/HappyFSCache.js

This fixes a problem where the cache was lost after a successful pickup of the cache. So to repro:
1. Run with happypack, generate cache
2. Run again, see the cache get picked up
3. Run again, see the cache go missing
With this patch, 3 successfully picks up the cache

Copy the currentContext into the cache when it's still valid

---

README.md
TODO.md
lib/HappyFakeCompiler.js
lib/HappyMessage.js
lib/HappyPlugin.js
lib/HappyTestUtils.js
lib/HappyThread.js
lib/HappyThreadPool.js
lib/HappyWorker.js
lib/HappyWorkerChannel.js
lib/__tests__/HappyPlugin.integration.test.js
lib/__tests__/HappyPlugin.test.js
lib/__tests__/HappyThread.test.js
lib/__tests__/HappyThreadPool.test.js
lib/__tests__/HappyWorkerChannel.test.js
lib/__tests__/integration/options__threadPool.test.js
lib/fnOnce.js

Multiple Happy plugin instances can now share the same thread pool. Very effective when some instances have way fewer files than others in which case their threads used to be idle most of the time.

shared thread pools, closes #5

---

README.md
lib/HappyFSCache.js
lib/HappyFakeLoaderContext.js
lib/HappyPlugin.js
lib/HappyRPCHandler.js
lib/__tests__/integration/RPC--Loader__emitFile.test.js

- support for `file-loader` which uses `this.emitFile()`
- loaders can now be inferred once more by supplying
{ happy: { id: '...' }  }
- a happy plugin can be disabled by passing { enabled: false } to its
config, useful for env variable-based control

this.emitFile() and re-introduced loader inference

---

lib/HappyPlugin.js

Using `grunt-webpack` with `grunt-contrib-watch` causes the "HappyPlugin has already been started!" message and hang the 2nd time it runs. Removing the assert fixes the issue but let me know if there is a better way...
p.s. great work on this!

Remove assert if already running

---

lib/HappyPlugin.js
lib/WebpackUtils.js
lib/__tests__/HappyPlugin.integration.test.js

Webpack supports defining query options for a loader as an object when
using the single-loader notation (module.loaders[].loader) which gets
JSON.stringified implicitly and passed down to the loader as a "query
string".
When HappyPack is expected to infer the loaders from webpack's config,
it has to take that query out and pass it down to the real loaders.
Prior to this patch, the query was left untouched and instead was being
passed to the *happy* loader (by webpack), which then gets confused by
those extraneous query params, preventing it from finding its plugin
instance.
Closes #26

Add support for "query" loader config

---

lib/HappyFSCache.js
lib/SourceMapSerializer.js

Sometimes get `Unexpected end of input` when running in our teams build system so these changes should handle JSON parsing errors.

Making the cache loader and SourceMapSerializer a bit more bullet proof

---

lib/HappyPlugin.js

Great library! Reduced our webpack build times by 200%
Our app has a lot of console messages on startup and it can get a bit cluttered with all the happypack logs, so I'm hoping to keep them hidden if config.verbose is set to false :)

Additional config.verbose check for startup message

---

lib/HappyLoader.js

I've commented the Loader hack, so that way when changes are made to fully support Webpack 2 the code can be easily removed, but in the meantime it won't error out.

Fixes #44 with temporary workaround for webpack2 watch

---

.travis.yml

This runs tests against latest versions, which is probably the intended behavior.

Removed semvar locks from travis

---

lib/HappyLoader.js

Hello,
I made it available to make 'plugins' in HappyLoader a function.
It may be useful for integration with webpack >= 2.1.0-beta.23 which has a new mechanism of loading options with LoaderOptionsPlugin
If we define LoaderOptionsPlugin as:
```
var plugins = [ new webpack.LoaderOptionsPlugin({
options: {
plugins: function () {return plugins;}
},
})
...
];
module.exports = {
entry: entries,
plugins: plugins
...
};
```
`plugins` will be available in HappyLoader, and HappyPack won't be broken.

Allow option 'plugins' to be a function in HappyLoader

---

lib/HappyPlugin.js

For some reason the resolver for the less loader and possibly the postcss loader resolver based on #109 and possibly the sass loader resolver from #95 return loader objects with only the path and query property but the css loader uses the request property of the loader which is just the concatenation of path and query.

Include request property in loaders

---

lib/HappyPlugin.js

When I was coding, I found that the '.happypack' folder would add new cache files but not deleting old ones. So I want to know why not just overwrite the old files which already expired? 
@amireh

Modifying the code does not produce new cache files

---

lib/HappyPlugin.js
lib/WebpackUtils.js
lib/__tests__/WebpackUtils.test.js

This PR fixes a bug when the user provides an object query that when stringified, contains the char `!`. For example:
``` js
plugins: [
new HappyPack({
loaders: [{
path: 'vue-loader',
query: {
loaders: {
scss: 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
}
}
}]
})
]
```
After stringification, the whole loader string (including the query) passed to `compiler.resolvers.loader.resolve` is:
```
vue-loader?{"loaders":{"scss":"vue-style-loader!css-loader!sass-loader?indentedSyntax"}}
```
After resolve, the following is then passed to `extractPathAndQueryFromString` ([L140](https://github.com/amireh/happypack/blob/master/lib/WebpackUtils.js#L140)):
```
/absolute/path/to/vue-loader?{"loaders":{"scss":"vue-style-loader!css-loader!sass-loader?indentedSyntax"}}
```
Now because the string …

Avoid unnecessary query parsing in WebpackUtils.resolveLoaders

---

lib/HappyFakeLoaderContext.js
lib/HappyLoader.js
lib/applyLoaders.js

While [the wiki page says HappyPack supports .minimize Loader API](https://github.com/amireh/happypack/wiki/Webpack-Loader-API-Support), it actually doesn't.
Submit changes to add ".minimize" support.
This option is used by a common-used plugin "webpack.optimize.UglifyJsPlugin", which sets `context.minimize = true`, ([check the code here](https://github.com/webpack/webpack/blob/v1.14.0/lib/optimize/UglifyJsPlugin.js#L142-L144)). Missing this support, css cannot get minified correctly.

Support for loader API .minimize

---

lib/HappyFSCache.js
lib/HappyPlugin.js
lib/__tests__/HappyPlugin.test.js

Expose cache.generateSignature to be called by plugin and passed
into cache.set.
Fixes #159

Fix permanently stale cache by computing signature before compile

---

lib/HappyThread.js

Change 'attemping' to 'attempting'.

Fix spelling mistake of HappyThread.js

---

examples/build-all.sh
examples/ts-loader--webpack2/package.json
examples/ts-loader--webpack2/src/fileWithoutError.ts
examples/ts-loader--webpack2/src/index.ts
examples/ts-loader--webpack2/tsconfig.json
examples/ts-loader--webpack2/webpack.config--raw.js
examples/ts-loader--webpack2/webpack.config.js

This should resolve https://github.com/amireh/happypack/issues/164
I'm afraid I can't run the test as I'm on Windows.  I've done my best to guess how it should work - may need your help there if it doesn't run.  Fingers crossed!

Added ts-loader example

---

CHANGELOG.md
lib/BufferedFd.js
lib/HappyPlugin.js
lib/HappyThread.js
lib/HappyThreadPool.js
lib/HappyWorkerChannel.js
lib/UnbufferedFd.js
lib/__tests__/HappyPlugin.integration.test.js
lib/__tests__/HappyThreadPool.test.js
lib/__tests__/HappyWorkerChannel.test.js
lib/processSend.js

refs GH-166
There seems to be a difference in how process.send() behaves with fork()
between platforms since on Windows if it's called a sufficiently large
number of times (on my box that's around 6k) the process simply hangs.
This does not seem to be the case on OS X or Linux.
The fix was to never invoke process.send() until its callback yields.

buffer process.send() calls on Windows

---

README.md

I can see that I am changing something that might imply changed support conditions for webpack 2 - but isn't that the defacto state of happypack?
If you just look at the github repo you get the impression that the latest version of webpack is 3.0.3 and not 4.0.1 and that 4.x is in beta still. That is why I am proposing this change and the other PR.

Update Faq wrt webpack 2/3

---

lib/HappyLoader.js
lib/WebpackUtils.js

@amireh for some reason, I wasn't able to run the tests on the project.  At first I thought it was because I'm on Windows but I also tried on OSX and it also failed.  I tried these changes my work project using both webpack 3 and webpack 4 and it works for both.  Let me know if any additional fixes are needed.

Update resolver and loader syntax to work with webpack 4
